[package]
name = "image-util"
version = "0.0.1"
authors = [ "Woyten Tielesch <woyten.tielesch@online.de>" ]

[dependencies]
image = "*"
nalgebra = "*"
num = "*"

[dev-dependencies]
math-util = { git = "https://github.com/Woyten/math-util.git" }